### PR TITLE
Multiple & recursive expand

### PR DESCRIPTION
**Pull request by javiacei**
# Expand multiple variables

Now you can expand multiple variables using  `$` and `${}`.

``` bash
MONGOLAB_AUTH=$MONGOLAB_USER:${MONGOLAB_PASSWORD}
```
# Recursive expand

``` bash
MONGOLAB_USER_RECURSIVELY=${MONGOLAB_USER}:${MONGOLAB_PASSWORD}
MONGOLAB_URI_RECURSIVELY=mongodb://${MONGOLAB_USER_RECURSIVELY}@...
```
# Multiple & recursive expand tests

Added more tests checking new functionalities.

### CODE REVIEW

**Comment by motdotla** [comment]
Thanks for this. I'll take a look soon.

**Comment by kshvmdn** [comment]
I needed this feature for a project I'm working on, so I've been playing around with it. It seems to be overwriting preset variables (correct me if I'm wrong, but [this is a bug](https://github.com/motdotla/dotenv#what-happens-to-environment-variables-that-were-already-set)).

Here's how I can reproduce it:

```sh
# .env
NODE_ENV=production
```

```sh
$ NODE_ENV=development node ./index.js
```

```js
// index.js
const dotenv = require('dotenv')
const dotenvExpand = require('dotenv-expand')

dotenv.config()
console.log(process.env.NODE_ENV) // => development (as expected)

dotenvExpand(dotenv.config())
console.log(process.env.NODE_ENV) // => production (??)
```

I've found a fix with [this](https://github.com/SamyRoad/dotenv-expand/blob/master/lib/main.js#L22:L28) block.

```js
for (var configKey in config) {
  var value = process.env[configKey] || config[configKey]
  if (value.substring(0, 2) === '\\$') {
    config[configKey] = value.substring(1)
  } else {
    config[configKey] = interpolate(value)
  }
}
```

The problem seems to be that `config` maps to the object that was returned by `dotenv.config`, which doesn't use the preset environment variables, rather the [parsed file contents](https://github.com/motdotla/dotenv/blob/master/lib/main.js#L36). This [isn't a bug](https://github.com/motdotla/dotenv#can-i-customizewrite-plugins-for-dotenv), but perhaps `dotenv.config` should return both the _compiled_ and _raw_ variables (maybe another option to choose between the two)? (cc @motdotla)

**Comment by niftylettuce** [comment]
Meh, this still isn't fixed and the readme is still outdated per #2?

**Comment by rastasheep** [comment]
Any news? please?

**Comment by eliseumds** [comment]
?

**Comment by motdotla** [comment]
Thank you everyone for this PR and for your patience. It just merged here: https://github.com/motdotla/dotenv-expand/pull/5

**Comment by motdotla** [comment]
Just published on npm as `4.0.0`.

@kshvmdn 😱 you are absolutely right. I'll look into that right now.

**Pull request merged**
