### PR TITLE
Add node cli preload require support

### LINKED ISSUE #28: Preload dotenv-expand
Is it possible to preload ```dotenv-expand``` like dotenv does it?
```
$ node -r dotenv/config your_script.js
```

### PR DESCRIPTION
**Pull request by Logikgate**
dotenv allows us to preload it via node -r dotenv/config my_script.js.  This is the recommended usage when using import instead of require. This pull request adds this same preload support to dotenv-expand and should close #28

### CODE REVIEW

**Comment by ericrallen** [comment]
Going to take a look at this one in the next couple of days. Sorry for the delay.

**Comment by Logikgate** [comment]
Hey @ericrallen have you had a chance to take a look at this?

**Comment by itoyama** [comment]
@motdotla @ericrallen Please merge this PR.

**Comment by jeanbenitezu** [comment]
> @motdotla @ericrallen Please merge this PR.

x2

**Comment by motdotla** [comment]
Merged. We will try to have released by end of the week.

**Comment by motdotla** [comment]
Released 🎉: https://github.com/motdotla/dotenv-expand/blob/master/CHANGELOG.md#800-2022-02-03

Thank you!

**Pull request merged**
