### PR TITLE
Command Substitution

### PR DESCRIPTION
**Pull request by nVitius**
I added code to this plugin to do command substitution like bash does: `$(some_command)`

My personal use case was that I wanted to have the version from package.json inside of a env var in my Vue app.
Using this update, you can do something like: `APP_VERSION="$(cat package.json | jq '.version')"`

I've added a simple test (using `echo`) and made sure that all other existing tests are still working.
I think this could be a really valuable addition to the plugin.

### CODE REVIEW

**Comment by Heziode** [comment]
You should add an option to allow enable/disable this feature, because the execution of command can be dangerous.

**Comment by nVitius** [comment]
@Heziode The easiest solution that occurs to me is adding a prefix to the keys. Something like: `EVAL_APP_VERSION`

What do you think?

**Comment by Heziode** [comment]
IMHO, it should be done with an option inside the conf object, like this:

https://github.com/motdotla/dotenv-expand/blob/de9e5cb0215495452f475f5be4dea1580b8217cd/lib/main.js#L5

This will also require to update the `inde.d.ts` (that also have a missing value that wil be fixed with #47):

https://github.com/motdotla/dotenv-expand/blob/de9e5cb0215495452f475f5be4dea1580b8217cd/index.d.ts#L3-L8

**Comment by nVitius** [comment]
My issue with using the config object is that some of the popular bundlers (namely [vue-cli](https://cli.vuejs.org/guide/mode-and-env.html#modes) and [parcel](https://parceljs.org/env.html)) use dotenv (and dotenv-expand) but don't expose any way to pass configuration options into it.

Also, dotenv itself doesn't seem to officially support custom config values like `ignorePorcessEnv`
Reference: https://github.com/motdotla/dotenv/blob/72fb66b051280ef5c2cc40ce4962ac4601f7f515/lib/main.js

**Comment by Heziode** [comment]
> My issue with using the config object is that some of the popular bundlers (namely vue-cli and parcel) use dotenv (and dotenv-expand) but don't expose any way to pass configuration options into it.

Indeed, I hadn't thought of that. Afterwards, nothing prevents you from adding it to your project.

For implemenation details, etc. I think that @motdotla is more relevant to answer, since it's his lib.

**Comment by aequasi** [comment]
Why not use the config value, with a fallback to an env variable itself if not set

`DOTENV_EVAL=false` or something

**Comment by nVitius** [comment]
@motdotla
Can we get your feedback on this PR please?

**Comment by motdotla** [comment]
@nVitius thank you so much for this contribution 💛

That said, we decided to move it to its own module here: https://github.com/motdotla/dotenv-eval

We should see that module grow in complexity as it handles any edge cases.

**Comment by nVitius** [comment]
@motdotla a lot of projects use dotenv through an external tool and don't have access to configure dotenv or add new dependencies. I use dotenv a lot in my vue projects and vue-cli handles loading in dotenv. There would be no way for me to leverage command substitution in this case. Have you given any thought on how that might be solved for?

**Comment by motdotla** [comment]
@nVitius very good point.

So does vue-cli already default include dotenv-expand?

**Comment by motdotla** [comment]
(a part of me is also starting to think that maybe expand's functionality should move directly into Dotenv's)

**Comment by Heziode** [comment]
> (a part of me is also starting to think that maybe expand's functionality should move directly into Dotenv's)

This is exactly what I did, when I rewrote your lib in Ada: https://github.com/Heziode/ada-dotenv

**Comment by ccmattr** [comment]
> (a part of me is also starting to think that maybe expand's functionality should move directly into Dotenv's)

It would be amazing if dotenv-expand and dotenv-eval could be included by default. Theres no reason to say the package users couldnt limit the functionality through configuration.

**Pull request closed without merging**
