### PR TITLE
Add missing type for ignoreProcessEnv

### PR DESCRIPTION
**Pull request by felixmosh**

### CODE REVIEW

**Comment by reagent** [comment]
I encountered this issue today -- any idea when this will be merged and released?  I'm using your branch for now, but having an official release would be ideal.

For people coming here because of this issue, you can pull from Felix's branch instead of NPM:

```
yarn add git://github.com/felixmosh/dotenv-expand#add-missing-type
```

**Comment by reagent** [comment]
Actually, I ended up just using the type in this PR to create my own custom typing in the meantime:

```ts
declare module 'dotenv-expand' {
  interface DotenvResult {
    ignoreProcessEnv?: boolean;
    error?: Error;
    parsed?: {
      [name: string]: string;
    };
  }

  function dotenv_expand(config: DotenvResult): DotenvResult;

  export = dotenv_expand;
}
```

**Review by walli55 — APPROVED** [review]

**Comment by felixmosh** [comment]
@walli55 ,can you merge it?

**Comment by motdotla** [comment]
@felixmosh big apologies for the massive delay here.

**Pull request merged**
